// Login
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT = "LOGOUT";
export const AUTHORIZATION_FAIL = "AUTHORIZATION_FAIL";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SET_USER = "SET_USER";
export const EXISTING_USER = "EXISTING_USER";
export const SET_NEW_USERS = "SET_NEW_USERS";
export const SET_TOAST = "SET_TOAST";

// Topic
export const TOPIC_ADDED = "TOPIC_ADDED";
export const TOPIC_FAIL = "TOPIC_FAIL";
export const TOPIC_EDITED = "TOPIC_EDITED";
export const TOPIC_DELETED = "TOPIC_DELETED";
export const SET_TOPIC_DATA = "SET_TOPIC_DATA";
export const SET_TOPIC_HAS_MORE = "SET_TOPIC_HAS_MORE";
export const TOPIC_COMMENT_ADDED = "TOPIC_COMMENT_ADDED";
export const TOPIC_COMMENT_EDITED = "TOPIC_COMMENT_EDITED";
export const TOPIC_COMMENT_DELETED = "TOPIC_COMMENT_DELETED";
export const TOPIC_COMMENT_FAIL = "TOPIC_COMMENT_FAIL";
export const TOPIC_LIKE_ADDED = "TOPIC_LIKE_ADDED";
export const TOPIC_LIKE_FAIL = "TOPIC_LIKE_FAIL";
export const TOPIC_LIKE_REMOVED = "TOPIC_LIKE_REMOVED";
export const TOPIC_DISLIKE_ADDED = "TOPIC_DISLIKE_ADDED";
export const TOPIC_DISLIKE_REMOVED = "TOPIC_DISLIKE_REMOVED";
export const SET_TOPIC_DETAILS = "SET_TOPIC_DETAILS";
export const SET_FETCHING_TOPIC_DETAILS = "SET_FETCHING_TOPIC_DETAILS";
export const SET_NEW_TOPICS = "SET_NEW_TOPICS";
